### ISSUE TITLE
Remove one nextSibling

### ISSUE THREAD

**Issue by gregoiresage** [fletchto99/Pebble-liveconfig#2]
https://github.com/fletchto99/Pebble-liveconfig/blob/master/web/liveconfig.js#L52

Also line 49 you can repalce `elem.nextSibling.nextSibling.firstChild.style.backgroundColor` by `elem .value`

**Comment by fletchto99** [comment]
The problem is the color picker, ins slate, never actually updates the value of the text input (at least to my knowledge, perhaps the latest version of slate fixes this issue). I will investigate further and report back on this issue.
