### ISSUE TITLE
oninput doesn't work for checkboxes

### ISSUE THREAD

**Issue by gregoiresage** [fletchto99/Pebble-liveconfig#3]
https://github.com/fletchto99/Pebble-liveconfig/blob/master/web/liveconfig.js#L37

You probably should use onchange instead

**Comment by fletchto99** [comment]
Thanks! I'll update the source to use onchange for the type checkbox.

**Comment by flocsy** [comment]
and the same for radiogroups, but there's another problem: the individual inputs don't have id-s
