### ISSUE TITLE
Is it broken ?

### ISSUE THREAD

**Issue by gregoiresage** [fletchto99/Pebble-liveconfig#5]
WebSocket connection to 'wss://liveconfig.fletchto99.com/receive/06247c7ab1a65cca3e87230ad85c8ef4/c49a5070d640fe3fe0a07df763b2dcbd' failed: Error during WebSocket handshake: Unexpected response code: 502

Will it be back ?

**Comment by fletchto99** [comment]
It should be back now. Let me know if there are any further issues. It appears the forwarding process crashed for some reason. I am investigating.
